# Generated by Django 4.1.7 on 2023-03-06 03:13

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import properties.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', properties.models.AddressField()),
                ('guest_num', models.IntegerField()),
                ('amenities', multiselectfield.db.fields.MultiSelectField(choices=[('Wifi', 'Wifi'), ('Kitchen', 'Kitchen'), ('Parking', 'Parking'), ('TV', 'TV'), ('Toiletries', 'Toiletries'), ('Workspace', 'Workspace'), ('Self-CheckIn', 'Self-CheckIn'), ('Free Cancellation Within 24 hours', 'Free Cancellation Within 24 hours'), ('Free Cancellation Within 48 hours', 'Free Cancellation Within 48 hours'), ('Free Cancellation Within one week', 'Free Cancellation Within one week')], max_length=159, validators=[properties.models.validate_min_choices])),
                ('description', models.TextField(max_length=500)),
                ('thumbnail_img', models.ImageField(upload_to='properties_thumbnails/')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Image_Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties_images/')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='Date_Price_Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pricing', models.FloatField()),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dates_prices', to='properties.property')),
            ],
            options={
                'unique_together': {('start_date', 'end_date', 'property')},
            },
        ),
    ]
