# Generated by Django 4.1.7 on 2023-03-05 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dates_prices',
            unique_together={('start_date', 'end_date', 'property')},
        ),
    ]
