# Generated by Django 4.1.7 on 2023-03-05 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_dates_prices_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dates_Prices',
            new_name='Dates_Prices_Properties',
        ),
        migrations.RenameModel(
            old_name='Images',
            new_name='Images_Properties',
        ),
    ]
