# Generated by Django 4.1.7 on 2023-03-06 03:13

import bookings.models
from django.db import migrations, models
import django.db.models.deletion
import properties.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_address', properties.models.AddressField()),
                ('contact_info', bookings.models.ContactInfo()),
                ('state', models.CharField(choices=[('Pending', 'Pending'), ('Denied', 'Denied'), ('Expired', 'Expired'), ('Approved', 'Approved'), ('Canceled', 'Canceled'), ('Terminated', 'Terminated'), ('Completed ', 'Completed')], default='Pending', editable=False, max_length=50)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to='users.customuser')),
                ('property_booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_book', to='properties.property')),
            ],
        ),
    ]
